INSERT INTO cards (
VALUES
(1, 'A buon cavalier non manca lancia', 'Дело мастера боится'),
(2, 'A buon rendere', 'Долг платежом красен'),
(3, 'A cavai donato non si guarda in bocca', 'Дарёному коню в зубы не смотрят'),
(4, 'A chi piaccion le belle e a chi le brutte; per questa strada si mar t a tutte', 'Ha всякий товар есть свой покупатель'),
(5, 'A chi vuole non mancan modi', 'Кто хочет, тот добьётся'),
(6, 'A tal coltello tal guaina', 'Каждому своё'),
(7, 'Anche le zoppe si maritano', 'Любовь зла'),
(8, 'Batti il ferro finché è caldo', 'Куй железо, пока горячо'),
(9, 'Beva la feccia chi ha bevuto il vino', 'Любишь кататься, люби и саночки возить'),
(10, 'Bisogno genera bisogno', 'Одно к одному'),
(11, 'Bue vecchio, solco dritto', 'Старый конь борозды не портит'),
(12, 'Buona notte, Gesù, che l''olio è caro', 'И дело с концом'),
(13, 'Burlando si dice il vero', 'В каждой шутке есть доля правды'),
(14, 'Caldo di panno non fa mai danno', 'Пар костей не ломит'),
(15, 'Chi a tutti facil crede, ingannato si vede', 'Доверяй, но проверяй'),
(16, 'Chi cambia la vecchia per la nuova, peggio trova', 'Старый друг лучше новых двух'),
(17, 'Chi dorme con i cani si leva con le pulci', 'С кем поведёшься, от того и наберёшься'),
(18, 'Chi ha ventura, poco senno gli basta', 'He родись красивой, a родись счастливой'),
(19, 'Con le mani di un''altro è facile toccare il fuoco', 'Чужими руками жар загребать'),
(20, 'Chi lingua ha a Roma va', 'Язык до Рима доведёт'),
(21, 'D'' un cattivo ceppo non può venire una buona scheggia', 'Яблоко от яблони недалеко падает'),
(22, 'D'' un uovo bianco spesso nasce un pulcino', 'В семье не без урода'),
(23, 'Da cattivo debitor togli paglia per lavor', 'С паршивой овцы хоть шерсти клок'),
(24, 'Dal canto si conosce l'' uccello', 'Видна птица по полёту'),
(25, 'Dal conto manca sempre il lupo', 'Это только цветочки, ягодки впереди'),
(26, 'Dal detto al fatto c''è un gran tratto', 'От слов до дела далеко'),
(27, 'Dal falso bene viene il vero male', 'Неискреннее добро оборачивается настоящим злом'),
(28, 'Dall'' asino non cercar la lana', 'Всё равно что требовать от козла молока'),
(29, 'E'' cambiato il maestro di cappella ma la musica è sempre quella', 'Музыканты новые, a музыка всё та же'),
(30, 'E chi dice ma, il cuore contento non ha', 'Кто сомневается, тот не может быть довольным'),
(31, 'E'' come ancora, che sta sempre nel mare e non impara mai a nuotare', 'Его учить — что с бороной по лесу ходить'),
(32, 'E'' come lavare il capo all''asino', 'Дурака учить — что мёртвого лечить'),
(33, 'E'' fatto a colpi d'' ascia', 'Неладно скроен, да крепко сшит'),
(34, 'Е'' Г illuminazione di frate cuio', 'Раньше было неясно, а теперь так и совсем не понять'),
(35, 'Fa come i cani', 'С него как с гуся вода'),
(36, 'Fa del bene e avrai sempre bene', 'Добро сеять — добро и пожинать'),
(37, 'Fa il tuo dovere e non temere', 'За правое дело стой смело'),
(38, 'Fammi fattore un anno, se sarò povero, mio danno', 'Глупо не воспользоваться тем, что само в руки плывёт'),
(39, 'Far le nozze coi fichi secchi', 'Дёшево и сердито'),
(40, 'Far mettere i denti alle ranocchie', 'Ждать, пока у лягушек зубы вырастут'),
(41, 'Gambe in spalla', 'Одна нога здесь, другая — там'),
(42, 'Gatto lo sa', 'Чёрт его разберёт'),
(43, 'Giovane ozioso, vecchio bisognoso', 'Кто смолоду бездельник, тот в старости в нужде'),
(44, 'Gioventù non ha virtù', 'Молодо-зелено — погулять велено'),
(45, 'Gli amici degli amici sono amici', 'Друзья наших друзей — наши друзья'),
(46, 'Gli anni dan senno', 'С годами ум крепчает'),
(47, 'Gli viene il panno per tutti i versi', 'Доброму вору всё впору'),
(48, 'Guardati dal villano che ha sempre camicia bianca', 'У работника и руки должны быть рабочими'),
(49, 'На bel mentire chi vien da lontano', 'Добро тому врать, кто за морем бывал'),
(50, 'I casi son tanti', 'Что только не случается'),
(51, 'I denari non si trovano per strada', 'Деньги на улице не валяются'),
(52, 'I giorni spesi bene sono i meglio impiegati', 'Лучшая трата времени — труд'),
(53, 'I muri parlano', 'И у стен есть уши'),
(54, 'I panni sporchi si lavano in famiglia', 'He выноси грязь из избы'),
(55, 'I quattrini non sporcano le dita', 'Деньги не пахнут'),
(56, 'Il bene bisogna cercarlo, e il male aspettarlo', 'Добра добивайся, a беды дожидайся'),
(57, 'Il tentare non nuoce', 'Попытка — не пытка'),
(58, 'In casa di calzolaio non si hanno scarpe', 'Сапожник без сапог'),
(59, 'In mancanza di cavalli gli asini trottano', 'Ha безрыбье и рак рыба'),
(60, 'Itibus, Prete Pioppo', 'Было, да сплыло'),
(61, 'L'' acqua corre alla china', 'Всё в мире идёт своим чередом'),
(62, 'L'' acqua corre, e il sangue tira', 'Родная кровь притягивает'),
(63, 'L'' amore è muto', 'Любви не надо слов'),
(64, 'L'' errore è dell'' uomo', 'Человеку свойственно ошибаться'),
(65, 'L'' uso vince natura', 'Стерпится — слюбится'),
(66, 'La botte dà del vin che ha', 'От дурака не жди добра'),
(67, 'La fiducia non s'' impone non si compra', 'Доверие нужно завоевать'),
(68, 'Mal delibera chi troppo teme', 'Страх — плохой советчик'),
(69, 'Mangiare a modo suo, vestire а mo'' degli altri', 'Ешь по-своему, одевайся как другие'),
(70, 'Meglio poco che niente', 'Лучше мало, чем ничего'),
(71, 'Meglio tardi che mai', 'Лучше поздно, чем никогда'),
(72, 'Mente sano in corpo sano', 'В здоровом теле здоровый дух'),
(73, 'Molto fumo e poco arrosto', 'Много слов и мало дела'),
(74, 'Misura sette volte e taglia una', 'Семь раз отмерь, один раз отрежь'),
(75, 'Ne ho pochi de'' santi in camera', 'Моё терпение на исходе'),
(76, 'Nella felicità gii altari non fumano', 'Счастливые о Боге забывают'),
(77, 'Nessuna meraviglia dura più di tre giorni', 'Любое чудо больше трёх дней не живёт'),
(78, 'Nessuna nuova, buona nuova', 'Нет известий — добрые вести'),
(79, 'Nessuno nasce maestro', 'Великими не рождаются'),
(80, 'Non c''è avere che valga sapere', 'Знания — дороже богатства'),
(81, 'О va о si spezza', 'Или пан, или пропал'),
(82, 'Oggi a me, domani a te', 'Ты мне, я тебе'),
(83, 'Occhio per occhio, dente per dente', 'Око за око, зуб за зуб'),
(84, 'Ogni campanile suona le sue campane', 'Каждый смотрит co своей колокольни'),
(85, 'Ogni bottega ha la sua malizia', 'В каждой лавке свой обман'),
(86, 'Ogni bene alfan svanisce, ma la fama mai perisce', 'Добрая слава лучше богатства'),
(87, 'Ogni genere musicorum', 'Всякой твари по паре'),
(88, 'Pan di figlioli pene e duoli', 'Сыновний хлеб горек'),
(89, 'Parere e non essere filare e non tessere', 'Хорош, пригож, да к делу не гож'),
(90, 'Pane e lavoro non manca mai', 'Была б охота, будет и работа'),
(91, 'Parole fan mercato, e i denari pagano', 'Уговор дороже денег'),
(92, 'Per amore non si sente dolore', 'Для милого ничто не в труд'),
(93, 'Per forza si fa l'' aceto', 'Через силу и конь не скачет'),
(94, 'Per i poltroni è sempre festa', 'Ленивому всегда праздник'),
(95, 'Qual gamba, tale calza', 'По ноге и обувка'),
(96, 'Quando casca la cupola', 'Когда рак на горе свистнет'),
(97, 'Quando il fico serba i! fico, buon villano serba il panico', 'Бережливость — лучшее богатство'),
(98, 'Quando non с'' è il gatto, i topi ballano', 'Кошка из дому — мышкам раздолье'),
(99, 'Quel ch'' è detto è detto', 'Сказанного не воротишь'),
(100, 'Quel che è differito non è perduto', 'Что отложено — не потеряно'),
(101, 'Ragazzi e polli non si trovan mai satolli', 'Подростков и цыплят досыта не накормишь'),
(102, 'Rama di palude sempre salva', 'Лягушка всегда в болоте выживет'),
(103, 'Ricchezza poco vale a quel che l''usa male', 'Глупому и богатство не впрок'),
(104, 'Ride bene chi ride l''ultimo', 'Хорошо смеётся тот, кто смеётся последним'),
(105, 'Risponde il frate come l''abate canta', 'Чей слуга — того и песенку поёт'),
(106, 'Roma non fu fatta in un giorno', 'Рим был создан не в один день'),
(107, 'S''impiccano i ladrucci e non i ladroni', 'Вешают мелких воришек, a не крупных воров'),
(108, 'Sapienza vecchia d à frutto nuovo', 'И старая наука приносит новые плоды'),
(109, 'Sasso tratto e parola detta non tornano indietro', 'Слово не воробей, вылетит — не поймаешь'),
(110, 'Sav''o da piccino, matto da grande', 'Умным родился, да дураком вырос'),
(111, 'Sbagliando s''impara', 'Ha ошибках учатся'),
(112, 'Scherza coi fanti e lascia stare i santi', 'Шути, да осторожно, a то в беду попасть можно'),
(113, 'Son santi che mangiano', 'Все мы люди, все мы человеки'),
(114, 'Tal pera mangia il padre, che al figliuolo allega i denti', 'За грехи отцов зачастую приходится расплачиваться детям'),
(115, 'Tempo è danaro', 'Время — деньги'),
(116, 'Testa fra le spalle, ma cervello fra nubi', 'Голова хоть на плечах, да витает в облаках'),
(117, 'Tra carne ed ugna nessun ci pugna', 'Свои собаки грызутся — чужая Не приставай'),
(118, 'Tra due mali scegli il minore', 'Из двух зол выбирай меньшее'),
(119, 'Tra moglie e marito non mettere il dito', 'Муж и жена — одна сатана'),
(120, 'Tutti i gusti son gusti', 'О вкусах не спорят'),
(121, 'Un bel tacere non nuoce', 'Умение молчать украшает человека'),
(122, 'Un poco di vero fa creder tutta la bugia', 'Немного правды заставляет поверить в любую ложь'),
(123, 'Una mosca ha mangiato un cavallo', 'Целый век прошёл'),
(124, 'Una ne paga cento', 'Семь бед — один ответ'),
(125, 'Una noce da sola, non suona nel sacco', 'Один в поле не воин'),
(126, 'Uno chi fa il letto deve trovarsi in esso', 'Кто платит, тот и заказывает музыку'),
(127, 'Uno dice pari, l''altro caffo', 'Один за здравие, другой за упокой'),
(128, 'Uno si diverte a grattarsi e l''altro si prende le sue pulci', 'Один заварил кашу, a другому приходится её расхлёбывать'),
(129, 'Uomo avvertito, mezzo salvo', 'Предупредить человека — наполовину спасти его'),
(130, 'Usa col buono e sta lungi dal cattivo', 'Доброго держись, a от худого удались'),
(131, 'Va la capra zoppa se il lupo non la intoppa', 'Всё до поры, до времени'),
(132, 'Val più un testimone di vista che mille d''udita', 'Лучше один раз увидеть, чем сто раз услышать'),
(133, 'Val più un''oncia d''onore che mille libbre d''oro', 'Честь дороже золота'),
(134, 'Verrà il nostro giorno', 'Будет и на нашей улице праздник'),
(135, 'Vesti un palo che bel t'' appare', 'В уборе и пень хорош'),
(136, 'Vino dentro, senno fuori', 'Что у трезвого на уме, то у пьяного на языке'),
(137, 'Vipera morta non morde seno, ma pur fa mal coll''odor del veleno', 'Зло надо вырывать с корнем'),
(138, 'Volere è potere', 'Кто хочет, тот может'),
(139, 'Volevi la bicicletta — pedala', 'Взялся за гуж — не говори, что не дюж'),
(140, 'Zitto come l’ olio', 'Тише воды, ниже травы')
);